from alembic import op

revision = "20261008_0033"
down_revision = "20261007_0032"
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE TABLE construction.construction_subcontracts (\n\tproject_id UUID NOT NULL,\n\tsupplier_person_id UUID NOT NULL,\n\tcode VARCHAR(50) NOT NULL,\n\ttitle VARCHAR(255) NOT NULL,\n\tvalid_from DATE NOT NULL,\n\tvalid_to DATE NOT NULL,\n\tstatus VARCHAR(20) DEFAULT 'DRAFT' NOT NULL,\n\tretention_rate NUMERIC(8, 4) DEFAULT '0' NOT NULL,\n\tescrow_rate NUMERIC(8, 4) DEFAULT '0' NOT NULL,\n\tescrow_due_date DATE,\n\treleased_version INTEGER DEFAULT '0' NOT NULL,\n\treleased_by_user_id UUID,\n\tnotes TEXT,\n\tclosure_reason TEXT,\n\tclosed_by_user_id UUID,\n\tid UUID NOT NULL,\n\tcompany_id UUID NOT NULL,\n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,\n\tupdated_at TIMESTAMP WITH TIME ZONE,\n\tCONSTRAINT pk_construction_subcontracts PRIMARY KEY (id),\n\tCONSTRAINT uq_subcontract_project_code UNIQUE (company_id, project_id, code),\n\tCONSTRAINT ck_construction_subcontracts_ck_subcontract_status CHECK (status IN ('DRAFT','RELEASED','CLOSED','CANCELED')),\n\tCONSTRAINT ck_construction_subcontracts_ck_subcontract_dates CHECK (valid_to >= valid_from),\n\tCONSTRAINT ck_construction_subcontracts_ck_subcontract_rates CHECK (retention_rate BETWEEN 0 AND 100 AND escrow_rate BETWEEN 0 AND 100),\n\tCONSTRAINT fk_construction_subcontracts_project_id_construction_projects FOREIGN KEY(project_id) REFERENCES construction.construction_projects (id)\n)")
    op.execute('CREATE INDEX ix_construction_construction_subcontracts_company_id ON construction.construction_subcontracts (company_id)')
    op.execute('CREATE INDEX ix_construction_construction_subcontracts_project_id ON construction.construction_subcontracts (project_id)')
    op.execute("CREATE TABLE construction.construction_subcontract_items (\n\tcontract_id UUID NOT NULL,\n\tsequence_number INTEGER NOT NULL,\n\tproduct_id UUID,\n\tdescription VARCHAR(500) NOT NULL,\n\tunit_of_measure VARCHAR(20) NOT NULL,\n\tquantity NUMERIC(20, 8) NOT NULL,\n\tmaterial_unit_price NUMERIC(20, 8) NOT NULL,\n\tlabor_unit_price NUMERIC(20, 8) NOT NULL,\n\tconsumed_quantity NUMERIC(20, 8) DEFAULT '0' NOT NULL,\n\tactive BOOLEAN DEFAULT 'true' NOT NULL,\n\tid UUID NOT NULL,\n\tcompany_id UUID NOT NULL,\n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,\n\tupdated_at TIMESTAMP WITH TIME ZONE,\n\tCONSTRAINT pk_construction_subcontract_items PRIMARY KEY (id),\n\tCONSTRAINT uq_subcontract_item_sequence UNIQUE (contract_id, sequence_number),\n\tCONSTRAINT ck_construction_subcontract_items_ck_subcontract_quantity CHECK (quantity > 0 AND consumed_quantity >= 0 AND consumed_quantity <= quantity),\n\tCONSTRAINT ck_construction_subcontract_items_ck_subcontract_prices CHECK (material_unit_price >= 0 AND labor_unit_price >= 0),\n\tCONSTRAINT fk_construction_subcontract_items_contract_id_construct_961a FOREIGN KEY(contract_id) REFERENCES construction.construction_subcontracts (id)\n)")
    op.execute('CREATE INDEX ix_construction_construction_subcontract_items_company_id ON construction.construction_subcontract_items (company_id)')
    op.execute('CREATE INDEX ix_construction_construction_subcontract_items_contract_id ON construction.construction_subcontract_items (contract_id)')
    op.execute('CREATE TABLE construction.construction_subcontract_versions (\n\tcontract_id UUID NOT NULL,\n\tversion_number INTEGER NOT NULL,\n\tsheet JSONB NOT NULL,\n\treleased_by_user_id UUID,\n\tid UUID NOT NULL,\n\tcompany_id UUID NOT NULL,\n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,\n\tupdated_at TIMESTAMP WITH TIME ZONE,\n\tCONSTRAINT pk_construction_subcontract_versions PRIMARY KEY (id),\n\tCONSTRAINT uq_subcontract_version UNIQUE (contract_id, version_number),\n\tCONSTRAINT fk_construction_subcontract_versions_contract_id_constr_15a9 FOREIGN KEY(contract_id) REFERENCES construction.construction_subcontracts (id)\n)')
    op.execute('CREATE INDEX ix_construction_construction_subcontract_versions_company_id ON construction.construction_subcontract_versions (company_id)')
    op.execute('CREATE INDEX ix_construction_construction_subcontract_versions_contract_id ON construction.construction_subcontract_versions (contract_id)')
    op.execute("CREATE TABLE construction.construction_subcontract_consumptions (\n\tcontract_item_id UUID NOT NULL,\n\tversion_id UUID NOT NULL,\n\tmeasurement_id UUID NOT NULL,\n\tmeasurement_item_id UUID NOT NULL,\n\tapproval_cycle INTEGER NOT NULL,\n\tquantity NUMERIC(20, 8) NOT NULL,\n\tmaterial_amount NUMERIC(14, 2) NOT NULL,\n\tlabor_amount NUMERIC(14, 2) NOT NULL,\n\tstatus VARCHAR(20) DEFAULT 'POSTED' NOT NULL,\n\treversed_by_user_id UUID,\n\treversed_at TIMESTAMP WITH TIME ZONE,\n\tid UUID NOT NULL,\n\tcompany_id UUID NOT NULL,\n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,\n\tupdated_at TIMESTAMP WITH TIME ZONE,\n\tCONSTRAINT pk_construction_subcontract_consumptions PRIMARY KEY (id),\n\tCONSTRAINT uq_subcontract_consumption_cycle UNIQUE (measurement_item_id, approval_cycle),\n\tCONSTRAINT ck_construction_subcontract_consumptions_ck_subcontract_a4e6 CHECK (quantity > 0 AND status IN ('POSTED','REVERSED')),\n\tCONSTRAINT fk_construction_subcontract_consumptions_contract_item__0ee2 FOREIGN KEY(contract_item_id) REFERENCES construction.construction_subcontract_items (id),\n\tCONSTRAINT fk_construction_subcontract_consumptions_version_id_con_f808 FOREIGN KEY(version_id) REFERENCES construction.construction_subcontract_versions (id),\n\tCONSTRAINT fk_construction_subcontract_consumptions_measurement_id_64fa FOREIGN KEY(measurement_id) REFERENCES construction.construction_measurements (id),\n\tCONSTRAINT fk_construction_subcontract_consumptions_measurement_it_b0b0 FOREIGN KEY(measurement_item_id) REFERENCES construction.construction_measurement_items (id)\n)")
    op.execute('CREATE INDEX ix_construction_construction_subcontract_consumptions_m_274a ON construction.construction_subcontract_consumptions (measurement_id)')
    op.execute('CREATE INDEX ix_construction_construction_subcontract_consumptions_c_c501 ON construction.construction_subcontract_consumptions (company_id)')
    op.execute('CREATE INDEX ix_construction_construction_subcontract_consumptions_c_0902 ON construction.construction_subcontract_consumptions (contract_item_id)')
    op.execute("CREATE TABLE construction.construction_subcontract_direct_bills (\n\tcontract_id UUID NOT NULL,\n\tpayable_document_id UUID NOT NULL,\n\tamount NUMERIC(14, 2) NOT NULL,\n\tdeducted_amount NUMERIC(14, 2) DEFAULT '0' NOT NULL,\n\tverified_by_user_id UUID,\n\tdocument_snapshot JSONB NOT NULL,\n\tstatus VARCHAR(20) DEFAULT 'ACTIVE' NOT NULL,\n\tid UUID NOT NULL,\n\tcompany_id UUID NOT NULL,\n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,\n\tupdated_at TIMESTAMP WITH TIME ZONE,\n\tCONSTRAINT pk_construction_subcontract_direct_bills PRIMARY KEY (id),\n\tCONSTRAINT ck_construction_subcontract_direct_bills_ck_subcontract_b70b CHECK (amount > 0 AND deducted_amount >= 0 AND deducted_amount <= amount),\n\tCONSTRAINT fk_construction_subcontract_direct_bills_contract_id_co_de3e FOREIGN KEY(contract_id) REFERENCES construction.construction_subcontracts (id)\n)")
    op.execute("CREATE UNIQUE INDEX uq_subcontract_direct_bill_document ON construction.construction_subcontract_direct_bills (company_id, payable_document_id) WHERE status='ACTIVE'")
    op.execute('CREATE INDEX ix_construction_construction_subcontract_direct_bills_c_cdea ON construction.construction_subcontract_direct_bills (contract_id)')
    op.execute('CREATE INDEX ix_construction_construction_subcontract_direct_bills_c_a8f0 ON construction.construction_subcontract_direct_bills (company_id)')
    op.execute("CREATE TABLE construction.construction_subcontract_deductions (\n\tmeasurement_id UUID NOT NULL,\n\tdirect_bill_id UUID NOT NULL,\n\tamount NUMERIC(14, 2) NOT NULL,\n\tstatus VARCHAR(20) DEFAULT 'DRAFT' NOT NULL,\n\tposted_at TIMESTAMP WITH TIME ZONE,\n\treversed_at TIMESTAMP WITH TIME ZONE,\n\tid UUID NOT NULL,\n\tcompany_id UUID NOT NULL,\n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,\n\tupdated_at TIMESTAMP WITH TIME ZONE,\n\tCONSTRAINT pk_construction_subcontract_deductions PRIMARY KEY (id),\n\tCONSTRAINT uq_subcontract_deduction_measurement_bill UNIQUE (measurement_id, direct_bill_id),\n\tCONSTRAINT ck_construction_subcontract_deductions_ck_subcontract_deduction CHECK (amount > 0 AND status IN ('DRAFT','POSTED','REVERSED')),\n\tCONSTRAINT fk_construction_subcontract_deductions_measurement_id_c_ab90 FOREIGN KEY(measurement_id) REFERENCES construction.construction_measurements (id),\n\tCONSTRAINT fk_construction_subcontract_deductions_direct_bill_id_c_f398 FOREIGN KEY(direct_bill_id) REFERENCES construction.construction_subcontract_direct_bills (id)\n)")
    op.execute('CREATE INDEX ix_construction_construction_subcontract_deductions_dir_998b ON construction.construction_subcontract_deductions (direct_bill_id)')
    op.execute('CREATE INDEX ix_construction_construction_subcontract_deductions_mea_592c ON construction.construction_subcontract_deductions (measurement_id)')
    op.execute('CREATE INDEX ix_construction_construction_subcontract_deductions_company_id ON construction.construction_subcontract_deductions (company_id)')
    op.execute('ALTER TABLE construction.construction_measurements ADD COLUMN subcontract_id UUID')
    op.execute('ALTER TABLE construction.construction_measurements ADD COLUMN subcontract_version_id UUID')
    op.execute("ALTER TABLE construction.construction_measurements ADD COLUMN approval_cycle INTEGER DEFAULT '0' NOT NULL")
    op.execute("ALTER TABLE construction.construction_measurements ADD COLUMN reversal_pending BOOLEAN DEFAULT 'false' NOT NULL")
    op.execute("ALTER TABLE construction.construction_measurements ADD COLUMN escrow_amount NUMERIC(14, 2) DEFAULT '0' NOT NULL")
    op.execute('ALTER TABLE construction.construction_measurements ADD COLUMN escrow_due_date DATE')
    op.execute("ALTER TABLE construction.construction_measurements ADD COLUMN direct_billing_amount NUMERIC(14, 2) DEFAULT '0' NOT NULL")
    op.execute("ALTER TABLE construction.construction_measurements ADD COLUMN retention_details JSONB DEFAULT '[]' NOT NULL")
    op.execute('ALTER TABLE construction.construction_measurements ADD CONSTRAINT fk_construction_measurements_subcontract_version_id_con_2c15 FOREIGN KEY(subcontract_version_id) REFERENCES construction.construction_subcontract_versions (id)')
    op.execute('ALTER TABLE construction.construction_measurements ADD CONSTRAINT fk_construction_measurements_subcontract_id_constructio_f449 FOREIGN KEY(subcontract_id) REFERENCES construction.construction_subcontracts (id)')
    op.execute('CREATE INDEX ix_construction_construction_measurements_subcontract_id ON construction.construction_measurements (subcontract_id)')
    op.execute('ALTER TABLE construction.construction_measurement_items ADD COLUMN subcontract_item_id UUID')
    op.execute('ALTER TABLE construction.construction_measurement_items ADD COLUMN quantity NUMERIC(20, 8)')
    op.execute('ALTER TABLE construction.construction_measurement_items ADD COLUMN contract_snapshot JSONB')
    op.execute('ALTER TABLE construction.construction_measurement_items ADD CONSTRAINT fk_construction_measurement_items_subcontract_item_id_c_6622 FOREIGN KEY(subcontract_item_id) REFERENCES construction.construction_subcontract_items (id)')
    op.execute('CREATE INDEX ix_construction_construction_measurement_items_subcontr_0b93 ON construction.construction_measurement_items (subcontract_item_id)')
    op.execute('ALTER TABLE construction.outbox_events ADD COLUMN lease_owner UUID')
    op.execute('ALTER TABLE construction.outbox_events ADD COLUMN lease_until TIMESTAMP WITH TIME ZONE')
    op.execute('ALTER TABLE construction.outbox_events ADD COLUMN next_attempt_at TIMESTAMP WITH TIME ZONE')


def downgrade():
    op.drop_column('outbox_events','next_attempt_at',schema="construction")
    op.drop_column('outbox_events','lease_until',schema="construction")
    op.drop_column('outbox_events','lease_owner',schema="construction")
    op.drop_column('construction_measurement_items','contract_snapshot',schema="construction")
    op.drop_column('construction_measurement_items','quantity',schema="construction")
    op.drop_column('construction_measurement_items','subcontract_item_id',schema="construction")
    op.drop_column('construction_measurements','retention_details',schema="construction")
    op.drop_column('construction_measurements','direct_billing_amount',schema="construction")
    op.drop_column('construction_measurements','escrow_due_date',schema="construction")
    op.drop_column('construction_measurements','escrow_amount',schema="construction")
    op.drop_column('construction_measurements','reversal_pending',schema="construction")
    op.drop_column('construction_measurements','approval_cycle',schema="construction")
    op.drop_column('construction_measurements','subcontract_version_id',schema="construction")
    op.drop_column('construction_measurements','subcontract_id',schema="construction")
    op.drop_table('construction_subcontract_deductions',schema="construction")
    op.drop_table('construction_subcontract_direct_bills',schema="construction")
    op.drop_table('construction_subcontract_consumptions',schema="construction")
    op.drop_table('construction_subcontract_versions',schema="construction")
    op.drop_table('construction_subcontract_items',schema="construction")
    op.drop_table('construction_subcontracts',schema="construction")
